[profile.default]
src = 'solidity/contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'tests/forge'
fs_permissions = [{ access = "read-write", path = "./"}]
cache_path = './forge_cache'
optimizer = true
optimizer-runs = 200
